# Generated by Django 4.0.5 on 2022-06-22 05:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chakula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='picture',
            field=cloudinary.models.CloudinaryField(default='default.png', max_length=255, verbose_name='picture'),
        ),
    ]
